### ISSUE TITLE
`console.log()` not working in latest `create-react-app` after installing web3uikit

### ISSUE THREAD

**Issue by unclebay143** [web3ui/web3uikit#593] opened 2022-05-17 12:20 UTC
### How it happened/How to recreate the issue

- Create a new React app with `npx create-react-app appName`
- Install moralis SDK and Web3UIKit `npm install moralis react-moralis web3uikit`
   - Warning error displayed in the console
      ![image](https://user-images.githubusercontent.com/58919619/168807767-e9c82bcb-1881-4922-b976-3dc29c7d7327.png)

- Try to `console.log` a value
  ![Screenshot 2022-05-17 at 12 39 29 PM](https://user-images.githubusercontent.com/58919619/168807633-eed9da71-0168-42dd-a979-f4be7bdf72f0.png)

- Error displayed on the webpage
   <img width="1253" alt="Screenshot 2022-05-17 at 12 39 19 PM" src="https://user-images.githubusercontent.com/58919619/168807643-ad8bbba6-277e-4526-8021-d2f7efc21190.png">

**Comment by BillyG83** [comment] 2022-05-17 12:58
hi @unclebay143 thanks for trying the kit. This is a concern. 

I see `console-browserify` in my `package.lock` but not in our dependancies which suggests to me that it is a problem with `npm install`

we highly recommend using `yarn` to install your dependencies.

Could you please consider:
- install yarn globally
- delete node modules from this project
- run `yarn` to install dependancies for this project
- run `yarn start` or `yarn storybook` whatever you use to start developing your app

and let me know if that works please? Oh and close issue this if it work please, TY!!

**Comment by unclebay143** [comment] 2022-05-17 16:03
Hi @BillyG83 

1. I just created a new project and installed the dependencies with `yarn` still throwing the same error.

2. I also created a new React app with `yarn create react-app appName` and installed dependencies with `yarn` and still throwing the same error.

**Comment by locothedev** [comment] 2022-05-17 19:43
@unclebay143 I could not reproduce this error. Please share your package.json with me

**Comment by unclebay143** [comment] 2022-05-17 20:13
Hi @locothedev, did your console.log worked?


```
{
  "name": "web3ui-kit",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^13.5.0",
    "moralis": "^1.7.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-moralis": "^1.3.5",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4",
    "web3uikit": "^0.1.145"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by aLIEzsss4** [comment] 2022-05-31 11:49
I also have the same mistakes, haven't you solved it for 2 weeks?

**Comment by unclebay143** [comment] 2022-06-01 09:12
> I also have the same mistakes, haven't you solved it for 2 weeks?

No update yet

**Comment by BillyG83** [comment] 2022-06-01 17:31
sorry @aLIEzsss4 and @unclebay143 our small team have been focused on our deadline to deliver the new FE of Moralis.

`console-browserify` is not a dependancy of the kit, so its one of `CRA` or a dependency of a dependency... basically we don't have the man power or the resources to fix these sort of issues that are not related to our code. So i have to say, sadly I will close this issue.

I really encourage you to dig deep into the problem and share the fix here if you find it as this is an open source repo that we have been working on mostly as a passion project. I hope you understand. TY for using the kit

**Closed by BillyG83** 2022-06-01 17:31 UTC
Labels: bug

**Comment by lantos-lgtm** [comment] 2022-06-15 13:42
> sorry @aLIEzsss4 and @unclebay143 our small team have been focused on our deadline to deliver the new FE of Moralis.
> 
> `console-browserify` is not a dependancy of the kit, so its one of `CRA` or a dependency of a dependency... basically we don't have the man power or the resources to fix these sort of issues that are not related to our code. So i have to say, sadly I will close this issue.
> 
> I really encourage you to dig deep into the problem and share the fix here if you find it as this is an open source repo that we have been working on mostly as a passion project. I hope you understand. TY for using the kit

Hi BillyG83, thanks for your efforts on this project

I appreciate that there isn't resource to solve this issue but you you please leave/reopen this issue so that others who find this issue can start to tackle it. 


Just so that others can find the issue on google.
Error:
node_modules/console-browserify/index.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
